In [1]:
import statsmodels.api as sm
from statsmodels.formula.api import ols
import pandas as pd
import numpy as np

In [2]:
df_election_data = pd.read_csv('election_data.csv')
df_population_data = pd.read_csv('population_data.csv')

In [3]:
df_district_results = df_election_data.iloc[0:-2]
df_district_results.head()

    Race     REP  Total Votes  prop_r_vote
0  TX_01  167734       231969     0.723088
1  TX_02  139012       262924     0.528716
2  TX_03  168775       311070     0.542563
3  TX_04  188003       248373     0.756938
4  TX_05  130404       209147     0.623504

In [4]:
df_population_data.head()

,Unnamed: 0,older_proportion,proportion_white,proportion_male,born_in_TX,mean_income,higher_education,unemployment_rate
0,District 01 Estimate,0.421819,0.770341,0.488964,0.773983,66809,0.297772,0.060640
1,District 02 Estimate,0.352724,0.676836,0.500970,0.651026,108618,0.490439,0.042236
2,District 03 Estimate,0.338312,0.685146,0.490954,0.555650,122057,0.612976,0.036385
3,District 04 Estimate,0.426503,0.812625,0.491080,0.725613,74581,0.315266,0.049219
4,District 05 Estimate,0.373478,0.773341,0.502425,0.769360,69802,0.265619,0.047108

In [5]:
df_population_data["prop_r_vote"] = df_district_results['prop_r_vote']

In [6]:
full_data = df_population_data
full_data.head()

,Unnamed: 0,older_proportion,proportion_white,proportion_male,born_in_TX,mean_income,higher_education,unemployment_rate,prop_r_vote
0,District 01 Estimate,0.421819,0.770341,0.488964,0.773983,66809,0.297772,0.060640,0.723088
1,District 02 Estimate,0.352724,0.676836,0.500970,0.651026,108618,0.490439,0.042236,0.528716
2,District 03 Estimate,0.338312,0.685146,0.490954,0.555650,122057,0.612976,0.036385,0.542563
3,District 04 Estimate,0.426503,0.812625,0.491080,0.725613,74581,0.315266,0.049219,0.756938
4,District 05 Estimate,0.373478,0.773341,0.502425,0.769360,69802,0.265619,0.047108,0.623504

In [7]:
# df_population_data.to_csv('/Users/jim_jack/Documents/mod_2_project/mod_2_project_ds102218/full_data.csv')

In [13]:
outcome = 'prop_r_vote'
predictors = full_data.drop([outcome,"Unnamed: 0","mean_income","higher_education"], axis=1)
pred_sum = "+".join(predictors.columns)
formula = outcome + "~" + pred_sum
formula

'prop_r_vote~older_proportion+proportion_white+proportion_male+born_in_TX+unemployment_rate'

In [14]:
#Initial Model; Note white/non-white population not well correlated
model = ols(formula= formula, data=full_data).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:            prop_r_vote   R-squared:                       0.792
Model:                            OLS   Adj. R-squared:                  0.757
Method:                 Least Squares   F-statistic:                     22.81
Date:                Wed, 05 Dec 2018   Prob (F-statistic):           2.14e-09
Time:                        16:42:35   Log-Likelihood:                 30.190
No. Observations:                  36   AIC:                            -48.38
Df Residuals:                      30   BIC:                            -38.88
Df Model:                           5
Covariance Type:            nonrobust
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
Intercept            -6.9696      1.402     -4.973      0.000      -9.832      -4.107
older_proportion      4.1938      0.629      6.669      0.000       2.909       5.478
proportion_white      0.0610      0.215      0.284      0.779      -0.378       0.500
proportion_male      13.4530      2.832      4.750      0.000       7.669      19.237
born_in_TX           -0.8836      0.344     -2.567      0.015      -1.587      -0.181
unemployment_rate    -2.1220      2.736     -0.776      0.444      -7.710       3.465
==============================================================================
Omnibus:                        1.247   Durbin-Watson:                   2.403
Prob(Omnibus):                  0.536   Jarque-Bera (JB):                1.107
Skew:                          -0.249   Prob(JB):                        0.575
Kurtosis:                       2.300   Cond. No.                         262.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [10]:
#Let's try to normalize our data:
def mean_income_normalizer(row):
    num = row['mean_income'] - row
    
    
    num = x - x.min
    denom = x.max-x.min
    
def unemployment(row):
    return int(row['Unemployed'])/int(row['Civilian labor force'].head(1))

In [11]:
#think about feature selection methods

In [12]:
#checks

# print(metrics.mean_absolute_error(y_test, y_pred))
# print(metrics.mean_squared_error(y_test, y_pred))
# print(np.sqrt(metrics.mean_squared_error(y_test, y_pred)))