In [1]:
import pandas as pd
import glob

In [2]:
df_sen = pd.read_csv('results_csvs/US_Sen.csv')
df_tx_gov = pd.read_csv('results_csvs/TX_Gov.csv')
df_tx_09 = pd.read_csv('results_csvs/TX_9.csv')
df_tx_30 = pd.read_csv('results_csvs/TX_30.csv')

In [3]:
df_tx_gov

,Unnamed: 0,County,REP,DEM,LIB,Total Votes,Registered Voters,Turn Out%,Provisional Ballots,Precincts Reported,Total Precincts
0,3,ALL COUNTIES,4638582,3528705,140125,8307412,15793257,52.60%,46090,7965,7965
1,5,ANDERSON,11710,2849,149,14708,28487,51.63%,76,23,23
2,7,ANDREWS,3400,687,38,4125,9574,43.08%,2,5,5
3,9,ANGELINA,19689,6401,243,26333,51751,50.88%,8,43,43
4,11,ARANSAS,7044,1782,106,8932,17308,51.60%,37,4,4
5,13,ARCHER,3259,323,28,3610,6317,57.14%,6,12,12
6,15,ARMSTRONG,822,59,14,895,1428,62.67%,0,9,9
7,17,ATASCOSA,8345,3649,157,12151,27338,44.44%,60,22,22
8,19,AUSTIN,8988,1894,123,11005,19406,56.70%,102,19,19
9,21,BAILEY,1239,348,17,1604,3727,43.03%,5,5,5
10,23,BANDERA,7866,1600,120,9586,15869,60.40%,7,11,11
11,25,BASTROP,16332,10392,640,27364,47438,57.68%,99,22,22
12,27,BAYLOR,1090,129,15,1234,2365,52.17%,4,5,5
13,29,BEE,4827,2259,90,7176,15883,45.18%,11,11,11
14,31,BELL,50992,33612,1434,86038,195760,43.95%,809,49,49
15,33,BEXAR,249781,283755,9791,543327,1098257,49.47%,202,753,753
16,35,BLANCO,4327,1349,115,5791,8504,68.09%,33,7,7
17,37,BORDEN,321,17,1,339,488,69.46%,0,8,8
18,39,BOSQUE,5929,1095,106,7130,12209,58.39%,60,12,12
19,41,BOWIE,20625,7336,281,28242,59618,47.37%,90,33,33
20,43,BRAZORIA,70139,39395,1633,111167,207446,53.58%,1412,27,27
21,45,BRAZOS,39141,23189,1369,63699,114377,55.69%,426,27,27
22,47,BREWSTER,2022,1930,96,4048,7292,55.51%,0,9,9
23,49,BRISCOE,556,58,9,623,1084,57.47%,0,6,6
24,51,BROOKS,658,1198,12,1868,5843,31.96%,0,10,10
25,53,BROWN,10635,1457,142,12234,23368,52.35%,15,20,20
26,55,BURLESON,5252,1275,68,6595,11782,55.97%,0,14,14
27,57,BURNET,14423,3692,340,18455,31072,59.39%,159,21,21
28,59,CALDWELL,6706,4496,223,11425,23777,48.05%,100,32,32
29,61,CALHOUN,4409,1627,82,6118,12835,47.66%,0,26,26
...,...,...,...,...,...,...,...,...,...,...,...
225,453,TITUS,5828,2010,96,7934,17020,46.61%,51,20,20
226,455,TOM GREEN,25705,8314,486,34505,66826,51.63%,391,20,20
227,457,TRAVIS,145105,318120,13311,476536,775950,61.41%,5112,159,159
228,459,TRINITY,4293,835,41,5169,11455,45.12%,7,21,21
229,461,TYLER,6033,965,67,7065,13725,51.47%,75,18,18
230,463,UPSHUR,11625,2175,193,13993,27708,50.50%,16,17,17
231,465,UPTON,859,148,8,1015,2116,47.96%,2,7,7
232,467,UVALDE,4747,3054,80,7881,17118,46.03%,63,15,15
233,469,VAL VERDE,5938,5205,128,11271,27972,40.29%,25,18,18
234,471,VAN ZANDT,15606,2148,190,17944,36982,48.52%,147,18,18
235,473,VICTORIA,19588,7238,303,27129,55473,48.90%,35,36,36
236,475,WALKER,12179,5311,266,17756,33422,53.12%,117,17,17
237,477,WALLER,10616,5774,168,16558,32584,50.81%,117,21,21
238,479,WARD,2198,689,34,2921,6522,44.78%,11,9,9
239,481,WASHINGTON,10526,2725,208,13459,23253,57.88%,67,22,22
240,483,WEBB,16286,32044,569,48899,130784,37.38%,194,69,69
241,485,WHARTON,9470,3327,107,12904,25132,51.34%,0,9,9
242,487,WHEELER,1682,126,13,1821,3415,53.32%,1,11,11
243,489,WICHITA,24787,8594,489,33870,81419,41.59%,75,62,62
244,491,WILBARGER,2721,685,50,3456,8134,42.48%,5,6,6
245,493,WILLACY,1931,2257,38,4226,12405,34.06%,12,18,18
246,495,WILLIAMSON,112023,89678,5285,206986,331985,62.34%,1895,60,60
247,497,WILSON,13700,3796,199,17695,32537,54.38%,45,17,17
248,499,WINKLER,1150,284,19,1453,3870,37.54%,4,6,6
249,501,WISE,19621,3182,302,23105,41749,55.34%,106,26,26
250,503,WOOD,14360,2313,149,16822,30065,55.95%,0,14,14
251,505,YOAKUM,1558,303,32,1893,4264,44.39%,0,7,7
252,507,YOUNG,5567,724,87,6378,11854,53.80%,96,9,9
253,509,ZAPATA,859,1290,15,2164,7587,28.52%,4,8,8
254,511,ZAVALA,747,2080,20,2847,8157,34.90%,0,7,7

In [4]:
df_tx_09.columns

Index(['Unnamed: 0', 'County', 'DEM', 'LIB', 'IND', 'IND.1', 'Total Votes',
       'Precincts Reported', 'Total Precincts'],
      dtype='object')

In [5]:
new_columns = ["REP","Total Votes","R_%"]
test_list = [df_sen,df_tx_09,df_tx_gov]

In [6]:
# path =r'C:\DRO\DCL_rawdata_files' # use your path
# allFiles = glob.glob(path + "/*.csv")

# list_ = []

# for file_ in allFiles:
#     df = pd.read_csv(file_,index_col=None, header=0)
#     list_.append(df)

In [7]:
#test adding information to a df outside of a for loop
df_list = []
for data in test_list:
    df_dict = {}
    if "REP" in data.columns:
        df_dict["REP"] = data[data["County"]=="ALL COUNTIES"]["REP"][0]
    else:
        df_dict["REP"] = 0
    df_dict["Total Votes"] =  data[data["County"]=="ALL COUNTIES"]["Total Votes"][0]
    df_list.append(df_dict)
    

pd.DataFrame(df_list)

       REP  Total Votes
0  4244204      8334221
1        0       152653
2  4638582      8307412

In [8]:
path = '/Users/jim_jack/Documents/mod_2_project/mod_2_project_ds102218/results_csvs'
allFiles = glob.glob(path + "/*.csv")
lower = str.rfind(allFiles[0],'/')+1
upper = str.rfind(allFiles[0],'.')
allFiles[0][lower:upper]

'TX_32'

In [9]:
test_name = 'Users/jim_jack/Documents/mod_2_project/mod_2_project_ds102218/results_csvs/TX_32.cs'
def file_name_finder(file_name):
    lower = str.rfind(file_name,'/')+1

    upper = str.rfind(file_name,'.')

    return file_name[lower:upper]

In [10]:
path = '/Users/jim_jack/Documents/mod_2_project/mod_2_project_ds102218/results_csvs'
allFiles = glob.glob(path + "/*.csv")
allFiles
# one = allFiles[7]
# df_one = pd.read_csv(one)
# df_one[df_one["County"]=="ALL COUNTIES"]

['/Users/jim_jack/Documents/mod_2_project/mod_2_project_ds102218/results_csvs/TX_32.csv',
 '/Users/jim_jack/Documents/mod_2_project/mod_2_project_ds102218/results_csvs/TX_26.csv',
 '/Users/jim_jack/Documents/mod_2_project/mod_2_project_ds102218/results_csvs/TX_27.csv',
 '/Users/jim_jack/Documents/mod_2_project/mod_2_project_ds102218/results_csvs/TX_33.csv',
 '/Users/jim_jack/Documents/mod_2_project/mod_2_project_ds102218/results_csvs/TX_19.csv',
 '/Users/jim_jack/Documents/mod_2_project/mod_2_project_ds102218/results_csvs/TX_25.csv',
 '/Users/jim_jack/Documents/mod_2_project/mod_2_project_ds102218/results_csvs/TX_31.csv',
 '/Users/jim_jack/Documents/mod_2_project/mod_2_project_ds102218/results_csvs/TX_30.csv',
 '/Users/jim_jack/Documents/mod_2_project/mod_2_project_ds102218/results_csvs/TX_24.csv',
 '/Users/jim_jack/Documents/mod_2_project/mod_2_project_ds102218/results_csvs/TX_18.csv',
 '/Users/jim_jack/Documents/mod_2_project/mod_2_project_ds102218/results_csvs/TX_20.csv',
 '/Users/jim_jack/Documents/mod_2_project/mod_2_project_ds102218/results_csvs/TX_34.csv',
 '/Users/jim_jack/Documents/mod_2_project/mod_2_project_ds102218/results_csvs/TX_35.csv',
 '/Users/jim_jack/Documents/mod_2_project/mod_2_project_ds102218/results_csvs/TX_21.csv',
 '/Users/jim_jack/Documents/mod_2_project/mod_2_project_ds102218/results_csvs/TX_23.csv',
 '/Users/jim_jack/Documents/mod_2_project/mod_2_project_ds102218/results_csvs/TX_22.csv',
 '/Users/jim_jack/Documents/mod_2_project/mod_2_project_ds102218/results_csvs/TX_36.csv',
 '/Users/jim_jack/Documents/mod_2_project/mod_2_project_ds102218/results_csvs/TX_8.csv',
 '/Users/jim_jack/Documents/mod_2_project/mod_2_project_ds102218/results_csvs/TX_9.csv',
 '/Users/jim_jack/Documents/mod_2_project/mod_2_project_ds102218/results_csvs/TX_4.csv',
 '/Users/jim_jack/Documents/mod_2_project/mod_2_project_ds102218/results_csvs/TX_5.csv',
 '/Users/jim_jack/Documents/mod_2_project/mod_2_project_ds102218/results_csvs/TX_7.csv',
 '/Users/jim_jack/Documents/mod_2_project/mod_2_project_ds102218/results_csvs/US_Sen.csv',
 '/Users/jim_jack/Documents/mod_2_project/mod_2_project_ds102218/results_csvs/TX_6.csv',
 '/Users/jim_jack/Documents/mod_2_project/mod_2_project_ds102218/results_csvs/TX_2.csv',
 '/Users/jim_jack/Documents/mod_2_project/mod_2_project_ds102218/results_csvs/TX_3.csv',
 '/Users/jim_jack/Documents/mod_2_project/mod_2_project_ds102218/results_csvs/TX_1.csv',
 '/Users/jim_jack/Documents/mod_2_project/mod_2_project_ds102218/results_csvs/TX_13.csv',
 '/Users/jim_jack/Documents/mod_2_project/mod_2_project_ds102218/results_csvs/TX_12.csv',
 '/Users/jim_jack/Documents/mod_2_project/mod_2_project_ds102218/results_csvs/TX_10.csv',
 '/Users/jim_jack/Documents/mod_2_project/mod_2_project_ds102218/results_csvs/TX_11.csv',
 '/Users/jim_jack/Documents/mod_2_project/mod_2_project_ds102218/results_csvs/TX_15.csv',
 '/Users/jim_jack/Documents/mod_2_project/mod_2_project_ds102218/results_csvs/TX_29.csv',
 '/Users/jim_jack/Documents/mod_2_project/mod_2_project_ds102218/results_csvs/TX_28.csv',
 '/Users/jim_jack/Documents/mod_2_project/mod_2_project_ds102218/results_csvs/TX_14.csv',
 '/Users/jim_jack/Documents/mod_2_project/mod_2_project_ds102218/results_csvs/TX_16.csv',
 '/Users/jim_jack/Documents/mod_2_project/mod_2_project_ds102218/results_csvs/TX_17.csv',
 '/Users/jim_jack/Documents/mod_2_project/mod_2_project_ds102218/results_csvs/TX_Gov.csv']

In [11]:
def create_summary_df():
    path = '/Users/jim_jack/Documents/mod_2_project/mod_2_project_ds102218/results_csvs'
    allFiles = glob.glob(path + "/*.csv")
    df_summary = []
    for data in allFiles:
        df_dict = {}
        local_df = pd.read_csv(data)
        df_dict['Race'] = file_name_finder(data)
        if "REP" in local_df.columns:
            df_dict['REP'] = local_df.iloc[0]["REP"]
        else:
            df_dict["REP"] = 0
        df_dict['Total Votes'] = local_df.iloc[0]["Total Votes"]
        df_summary.append(df_dict)
    return pd.DataFrame(df_summary)

In [12]:
df_draft = create_summary_df()
df_draft

        REP    Race  Total Votes
0    125600   TX_32       273909
1    185268   TX_26       311860
2    124958   TX_27       207079
3     26007   TX_33       118609
4    152012   TX_19       201953
5    162288   TX_25       302700
6    144393   TX_31       285191
7         0   TX_30       182420
8    132992   TX_24       262433
9     38306   TX_18       183978
10        0   TX_20       170976
11    57157   TX_34       142804
12    50276   TX_35       192816
13   176913   TX_21       351430
14   102903   TX_23       209058
15   152368   TX_22       296449
16   160783   TX_36       221534
17   200367    TX_8       272732
18        0    TX_9       152653
19   188003    TX_4       248373
20   130404    TX_5       209147
21   115418    TX_7       242986
22  4244204  US_Sen      8334221
23   135779    TX_6       255543
24   139012    TX_2       262924
25   168775    TX_3       311070
26   167734    TX_1       231969
27   168090   TX_13       206093
28   172205   TX_12       267807
29   154807   TX_10       304111
30   174749   TX_11       217883
31    63593   TX_15       164284
32    28045   TX_29       117246
33        0   TX_28       138825
34   137582   TX_14       231873
35    48495   TX_16       179619
36   134375   TX_17       236364
37  4638582  TX_Gov      8307412

In [13]:
def add_leading_zero(row):
    if len(row) == 4:
        return row[0:3] +str(0) + row[-1] 
    else:
        return row

In [14]:
df_draft["Race"] = df_draft["Race"].apply(add_leading_zero)
df_draft
# df.loc[df['First Season'] > 1990, 'First Season'] = 1

        REP    Race  Total Votes
0    125600   TX_32       273909
1    185268   TX_26       311860
2    124958   TX_27       207079
3     26007   TX_33       118609
4    152012   TX_19       201953
5    162288   TX_25       302700
6    144393   TX_31       285191
7         0   TX_30       182420
8    132992   TX_24       262433
9     38306   TX_18       183978
10        0   TX_20       170976
11    57157   TX_34       142804
12    50276   TX_35       192816
13   176913   TX_21       351430
14   102903   TX_23       209058
15   152368   TX_22       296449
16   160783   TX_36       221534
17   200367   TX_08       272732
18        0   TX_09       152653
19   188003   TX_04       248373
20   130404   TX_05       209147
21   115418   TX_07       242986
22  4244204  US_Sen      8334221
23   135779   TX_06       255543
24   139012   TX_02       262924
25   168775   TX_03       311070
26   167734   TX_01       231969
27   168090   TX_13       206093
28   172205   TX_12       267807
29   154807   TX_10       304111
30   174749   TX_11       217883
31    63593   TX_15       164284
32    28045   TX_29       117246
33        0   TX_28       138825
34   137582   TX_14       231873
35    48495   TX_16       179619
36   134375   TX_17       236364
37  4638582  TX_Gov      8307412

In [15]:
df_cleaned = df_draft.set_index("Race")
df_sorted = df_cleaned.sort_index()
df_sorted

            REP  Total Votes
Race
TX_01    167734       231969
TX_02    139012       262924
TX_03    168775       311070
TX_04    188003       248373
TX_05    130404       209147
TX_06    135779       255543
TX_07    115418       242986
TX_08    200367       272732
TX_09         0       152653
TX_10    154807       304111
TX_11    174749       217883
TX_12    172205       267807
TX_13    168090       206093
TX_14    137582       231873
TX_15     63593       164284
TX_16     48495       179619
TX_17    134375       236364
TX_18     38306       183978
TX_19    152012       201953
TX_20         0       170976
TX_21    176913       351430
TX_22    152368       296449
TX_23    102903       209058
TX_24    132992       262433
TX_25    162288       302700
TX_26    185268       311860
TX_27    124958       207079
TX_28         0       138825
TX_29     28045       117246
TX_30         0       182420
TX_31    144393       285191
TX_32    125600       273909
TX_33     26007       118609
TX_34     57157       142804
TX_35     50276       192816
TX_36    160783       221534
TX_Gov  4638582      8307412
US_Sen  4244204      8334221

In [16]:
def prop_r_vote(row):
    return int(row['REP'])/int(row['Total Votes'])
df_sorted['prop_r_vote'] = df_sorted.apply(lambda row: prop_r_vote(row),axis=1)

In [17]:
df_sorted

            REP  Total Votes  prop_r_vote
Race
TX_01    167734       231969     0.723088
TX_02    139012       262924     0.528716
TX_03    168775       311070     0.542563
TX_04    188003       248373     0.756938
TX_05    130404       209147     0.623504
TX_06    135779       255543     0.531335
TX_07    115418       242986     0.474999
TX_08    200367       272732     0.734666
TX_09         0       152653     0.000000
TX_10    154807       304111     0.509048
TX_11    174749       217883     0.802031
TX_12    172205       267807     0.643019
TX_13    168090       206093     0.815603
TX_14    137582       231873     0.593351
TX_15     63593       164284     0.387092
TX_16     48495       179619     0.269988
TX_17    134375       236364     0.568509
TX_18     38306       183978     0.208210
TX_19    152012       201953     0.752710
TX_20         0       170976     0.000000
TX_21    176913       351430     0.503409
TX_22    152368       296449     0.513977
TX_23    102903       209058     0.492222
TX_24    132992       262433     0.506766
TX_25    162288       302700     0.536135
TX_26    185268       311860     0.594074
TX_27    124958       207079     0.603432
TX_28         0       138825     0.000000
TX_29     28045       117246     0.239198
TX_30         0       182420     0.000000
TX_31    144393       285191     0.506303
TX_32    125600       273909     0.458546
TX_33     26007       118609     0.219267
TX_34     57157       142804     0.400248
TX_35     50276       192816     0.260746
TX_36    160783       221534     0.725771
TX_Gov  4638582      8307412     0.558367
US_Sen  4244204      8334221     0.509250

In [20]:
# df_sorted.to_csv('/Users/jim_jack/Documents/mod_2_project/mod_2_project_ds102218/election_data.csv')